#!/usr/bin/env python3
# Copyright 2026 Zyvor AI Labs · https://zyvor.dev
# SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0

"""Generate the EC2-compatible API action and filter tables in docs/cloud-ec2-api.md.

The list of actions and filters is read from the Rust sources (the `match action` arms of the four dispatchers and
`FILTER_SPECS`), so an action added or removed in code shows up here and `--check` (used by CI-style checks) fails until
the document is regenerated. The status and note of each action are judgements made by reading the handlers; they live
in the STATUS table below and every entry is checked against the code: an entry for an action that no longer exists is
an error, and an action without an entry is reported as `real` (read the handler before relying on that).

    python3 scripts/ec2/action_table.py            # rewrite the generated block in docs/cloud-ec2-api.md
    python3 scripts/ec2/action_table.py --check    # exit 1 when the block is out of date
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "controller/src/api/ec2"
DOC = ROOT / "docs/cloud-ec2-api.md"
BEGIN = "<!-- actions:begin (generated by scripts/ec2/action_table.py; do not edit by hand) -->"
END = "<!-- actions:end -->"

# status -> meaning
LEGEND = [
    ("real", "does the work through the same code the REST API and the web UI use"),
    ("recorded", "stored and read back, so a client sees no difference; nothing in the guest or the data plane changes"),
    ("plan", "a stored plan: validated and listed, but no host forwards or filters traffic because of it (`forwardingActive=false`)"),
    ("fixed", "answers a fixed or empty list in the right shape"),
    ("mixed", "some parameters are enforced, some only recorded, some refused; the section named in the note says which"),
    ("refused", "always an error (`UnsupportedOperation` unless the note names another code)"),
]

# Actions that are not AWS actions (Machina's own, on the `ec2` service).
MACHINA = set("""AbortExperiment AllocateSubnetAddress ConfigureHealthCheck ConvergeStack CreateBackup
CreateBackupSchedule CreateMaintenanceSchedule CreateProject CreateRestorePoint CreateScheduledJob CreateVmSchedule CreateWebhook
DeleteBackupSchedule DeleteMaintenanceSchedule DeleteScheduledJob DeleteStack DeleteVmSchedule DeleteWebhook
DeregisterInstancesFromLoadBalancer DescribeAudit DescribeBackupSchedules DescribeBackups DescribeCapacity DescribeConsolidation
DescribeCostEstimate DescribeExperiments DescribeHaStatus DescribeInstanceGroups DescribeLoadBalancerMembers
DescribeMaintenanceSchedules DescribeMigrationJobs DescribeNotifications DescribePlacement DescribeProjects DescribeRestorePoints
DescribeRightsizing DescribeScheduledJobs DescribeSleepPolicies DescribeStackDrift DescribeStacks DescribeVmSchedules
DescribeWebhooks FenceHost ForkInstance ModifySleepPolicy ProposeConsolidation ProposeResize RegisterInstancesWithLoadBalancer
ReleaseSubnetAddress RestoreBackup RewindInstance RunExperiment SetStackAutoHeal SleepInstances UpdateInstanceGroup VerifyBackup
WakeInstances""".split())

# (service, action) -> (status, note). Anything missing is `real`.
S = {}


def put(service, names, status, note=""):
    for n in names.split():
        S[(service, n)] = (status, note)


# ---- ec2 -------------------------------------------------------------------------------------------------------
put("ec2", "RunInstances", "mixed", "Run, terminate and tags: each option is applied or refused, none dropped")
put("ec2", "ModifyInstanceAttribute DescribeInstanceAttribute", "mixed", "Instance attributes table")
put("ec2", "ModifyInstanceMetadataOptions", "mixed", "`HttpEndpoint=disabled` enforced by the agent; hop limit recorded; `HttpTokens=required` refused")
put("ec2", "MonitorInstances UnmonitorInstances", "recorded", "metrics are always collected at one granularity")
put("ec2", "CreateVolume ModifyVolume", "mixed", "size is real; type, IOPS, throughput recorded; `Encrypted`, `KmsKeyId`, `MultiAttachEnabled` refused")
put("ec2", "ModifyVolumeAttribute", "real", "delete-on-termination and IO limits")
put("ec2", "GetConsoleOutput", "real", "the instance's QEMU log, not the guest's serial output")
put("ec2", "GetConsoleScreenshot", "refused")
put("ec2", "CopySnapshot", "refused", "a copy would share the original's backing snapshot")
put("ec2", "CreateVpcEndpoint", "refused")
put("ec2", "GetPasswordData DescribeInstanceCreditSpecifications", "fixed", "empty / `standard`")
put("ec2", "DescribeEgressOnlyInternetGateways DescribePrefixLists DescribeManagedPrefixLists DescribeVpcEndpoints", "fixed", "always empty (what Terraform reads while refreshing a VPC)")
put("ec2", "DescribeSpotPriceHistory", "fixed", "flat synthetic price (0.005 per vCPU-hour), labelled in the reply")
put("ec2", "RequestSpotInstances", "mixed", "one-time requests only; launches at once; there is no price market")
put("ec2", "CancelSpotInstanceRequests", "real", "marks the request cancelled; the instance keeps running")
put("ec2", "CreateFleet", "mixed", "`Type=instant` only; `maintain` and `request` refused")
put("ec2", "CreateKeyPair", "mixed", "ed25519 only; `KeyType=rsa` and `KeyFormat=ppk` refused")
put("ec2", "RegisterImage CopyImage", "mixed", "from a snapshot / same region only; `ImageLocation` refused")
put("ec2", "CreateImage DeregisterImage ModifyImageAttribute", "real")
put("ec2", "CreateSnapshot CreateSnapshots", "mixed", "Atlas-backed volumes only; a local-pool volume is refused")
put("ec2", "CreateLaunchTemplate CreateLaunchTemplateVersion", "mixed", "template data holds only the `RunInstances` parameters Machina applies; others refused when written")
put("ec2", "CreatePlacementGroup", "mixed", "`cluster` and `spread`; `partition` refused")
put("ec2", "DescribeInstanceTypeOfferings DescribeInstanceTypes DescribeRegions DescribeAvailabilityZones DescribeAccountAttributes", "real", "derived from flavors and hosts; a zone is a host")
put("ec2", "CreateInternetGateway DeleteInternetGateway DescribeInternetGateways AttachInternetGateway DetachInternetGateway", "plan", "one per VPC; a route to a detached gateway shows `blackhole`")
put("ec2", "CreateNatGateway DeleteNatGateway DescribeNatGateways", "real", "real through a `0.0.0.0/0` route: it switches the host masquerade of the subnets using that table; public NAT only")
put("ec2", "CreateRouteTable DeleteRouteTable DescribeRouteTables AssociateRouteTable DisassociateRouteTable ReplaceRouteTableAssociation CreateRoute ReplaceRoute DeleteRoute", "plan", "a `0.0.0.0/0` route to a NAT gateway is the one route with an effect (see NAT gateway)")
put("ec2", "CreateNetworkAcl DeleteNetworkAcl DescribeNetworkAcls CreateNetworkAclEntry ReplaceNetworkAclEntry DeleteNetworkAclEntry ReplaceNetworkAclAssociation", "plan", "no host filters traffic by an ACL")
put("ec2", "CreateVpcPeeringConnection AcceptVpcPeeringConnection DescribeVpcPeeringConnections", "plan", "status `planned`; nothing forwards packets")
put("ec2", "CreateDhcpOptions DescribeDhcpOptions AssociateDhcpOptions DeleteDhcpOptions", "recorded", "no guest receives these options")
put("ec2", "ModifyVpcAttribute", "recorded", "`enableDnsHostnames` only; `enableDnsSupport=false` refused")
put("ec2", "AssignPrivateIpAddresses UnassignPrivateIpAddresses AllocateSubnetAddress ReleaseSubnetAddress", "recorded", "reserved in the subnet's address pool; not configured in the guest")
put("ec2", "AttachNetworkInterface DetachNetworkInterface", "real", "runs the real NIC tasks")
put("ec2", "CreateVpc", "real", "needs Machina's `ProjectId` and `AvailabilityZone` or `HostId`")
put("ec2", "ModifyNetworkInterfaceAttribute", "mixed", "`Description` and one `SecurityGroupId`; source/destination check cannot be turned off")
put("ec2", "DescribeLoadBalancers CreateLoadBalancer DeleteLoadBalancer", "real", "the native layer-4 balancer, not ELBv2 (use `elasticloadbalancing` for that)")
put("ec2", "DescribeAlarms PutMetricAlarm DeleteAlarms EnableAlarmActions DisableAlarmActions GetMetricStatistics", "real", "also answered by the `monitoring` service, in CloudWatch's shape")
put("ec2", "DescribeInstanceStatus", "real", "host-observed state; no second probe")
put("ec2", "ProposeResize ProposeConsolidation", "real", "files an approval action; nothing is resized or moved by the call")
put("ec2", "AuthorizeSecurityGroupIngress AuthorizeSecurityGroupEgress RevokeSecurityGroupIngress RevokeSecurityGroupEgress ModifySecurityGroupRules", "mixed", "IPv6 and prefix-list peers refused")

# ---- monitoring ------------------------------------------------------------------------------------------------
put("monitoring", "DescribeAlarms PutMetricAlarm DeleteAlarms EnableAlarmActions DisableAlarmActions GetMetricStatistics", "real", "CloudWatch shape compared with the documented one only by unit tests")

# ---- autoscaling -----------------------------------------------------------------------------------------------
put("autoscaling", "DescribeAccountLimits DescribeAdjustmentTypes DescribeTerminationPolicyTypes DescribeAutoScalingNotificationTypes DescribeScalingProcessTypes DescribeMetricCollectionTypes", "fixed")
put("autoscaling", "DescribeLifecycleHooks DescribeNotificationConfigurations DescribeScheduledActions DescribeInstanceRefreshes DescribeLoadBalancers DescribeLoadBalancerTargetGroups DescribeWarmPool", "fixed", "always empty")
put("autoscaling", "EnterStandby ExitStandby", "refused", "detach the instance instead")
put("autoscaling", "EnableMetricsCollection DisableMetricsCollection", "refused")
put("autoscaling", "PutLifecycleHook PutNotificationConfiguration PutScheduledUpdateGroupAction PutWarmPool StartInstanceRefresh AttachLoadBalancers AttachLoadBalancerTargetGroups SetInstanceProtection SetInstanceHealth", "refused")
put("autoscaling", "CreateAutoScalingGroup UpdateAutoScalingGroup", "mixed", "one subnet, `EC2` health checks, `Default` termination policy; other options refused")
put("autoscaling", "CreateLaunchConfiguration", "mixed", "`InstanceMonitoring.Enabled=true`, security groups, block devices, spot price, public IP refused")
put("autoscaling", "PutScalingPolicy", "mixed", "simple, step and target tracking (the CPU target); other metrics refused")
put("autoscaling", "SuspendProcesses ResumeProcesses", "mixed", "`Launch` and `Terminate` together pause the group; either alone is refused")

# ---- elasticloadbalancing --------------------------------------------------------------------------------------
put("elasticloadbalancing", "CreateRule SetRulePriorities", "refused", "only each listener's default rule exists (`SetRulePriorities` is a `ValidationError`)")
put("elasticloadbalancing", "DeleteRule", "refused", "the default rule is `OperationNotPermitted`")
put("elasticloadbalancing", "ModifyRule", "mixed", "the default rule's target group only; conditions refused")
put("elasticloadbalancing", "DescribeSSLPolicies DescribeAccountLimits", "fixed", "two policies, listed only / fixed numbers")
put("elasticloadbalancing", "ModifyLoadBalancerAttributes ModifyTargetGroupAttributes ModifyListenerAttributes", "mixed", "`deletion_protection.enabled` enforced; behaviour Machina lacks refused when switched on; the rest recorded")
put("elasticloadbalancing", "CreateLoadBalancer CreateTargetGroup CreateListener ModifyListener ModifyTargetGroup", "mixed", "layer-4 only: see the refused list in the ELBv2 section")


def read(name):
    return (SRC / name).read_text()


def fn_body(text, signature):
    i = text.index(signature)
    j = text.index("\n}\n", i)
    return text[i:j]


ARM = re.compile(r'^\s*((?:"[A-Za-z0-9]+"\s*\|?\s*)+)(?:if [^\n]*?)?=>', re.M)


def arms(body):
    out = []
    for m in ARM.finditer(body):
        out += re.findall(r'"([A-Za-z0-9]+)"', m.group(1))
    return out


def actions():
    ec2 = sorted(set(arms(fn_body(read("mod.rs"), "async fn dispatch("))))
    mon = sorted(set(arms(fn_body(read("services.rs"), "async fn monitoring_dispatch("))))
    asg = sorted(set(arms(fn_body(read("autoscaling.rs"), "pub async fn dispatch("))))
    elb = sorted(set(arms(fn_body(read("elbv2.rs"), "pub async fn dispatch("))))
    return {"ec2": ec2, "monitoring": mon, "autoscaling": asg, "elasticloadbalancing": elb}


def filters():
    text = read("foundation.rs")
    block = text[text.index("pub const FILTER_SPECS"):text.index("fn spec_for")]
    rows = []
    for m in re.finditer(r'action:\s*"(\w+)",(.*?)(?=\n    FilterSpec|\n\];)', block, re.S):
        action, rest = m.group(1), m.group(2)
        names = re.findall(r'(?:native|field)\("([\w.\-]+)"', rest)
        tags = "native_tags: true" in rest
        rows.append((action, names))
    # one-line specs
    for m in re.finditer(r'FilterSpec \{ action: "(\w+)", native_tags: (\w+), filters: &\[(.*?)\] \}', block):
        names = re.findall(r'(?:native|field)\("([\w.\-]+)"', m.group(3))
        rows.append((m.group(1), names))
    seen = {}
    for a, n in rows:
        seen.setdefault(a, n)
    return sorted(seen.items())


def render():
    acts = actions()
    for (svc, name) in S:
        if name not in acts[svc]:
            sys.exit(f"STATUS has an entry for {svc} {name}, which is not in the action match: remove or fix it")
    lines = []
    lines.append(BEGIN)
    lines.append("")
    lines.append("Status of each action (judged by reading its handler; **none of this has been run with a real client**, see *What has been run*):")
    lines.append("")
    for k, v in LEGEND:
        lines.append(f"- `{k}`: {v}")
    lines.append("")
    lines.append("An action that is not in these tables answers `UnsupportedOperation` on `ec2` and `InvalidAction` on the other services.")
    titles = {
        "ec2": ("ec2", "scope `ec2`, `POST /ec2`"),
        "monitoring": ("monitoring", "scope `monitoring`, `POST /monitoring`"),
        "autoscaling": ("autoscaling", "scope `autoscaling`, `POST /autoscaling`"),
        "elasticloadbalancing": ("elasticloadbalancing (ELBv2)", "scope `elasticloadbalancing`, `POST /elbv2`"),
    }
    for svc in ["ec2", "autoscaling", "elasticloadbalancing", "monitoring"]:
        title, scope = titles[svc]
        names = acts[svc]
        counts = {}
        for n in names:
            st = S.get((svc, n), ("real", ""))[0]
            counts[st] = counts.get(st, 0) + 1
        summary = ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))
        lines.append("")
        lines.append(f"### {title} actions ({len(names)}: {summary})")
        lines.append("")
        lines.append(f"Reached with {scope}.")
        lines.append("")
        if svc == "ec2":
            lines.append("`M` in the last column marks Machina's own actions (not AWS ones); a stock SDK has no call for them.")
            lines.append("")
            lines.append("| Action | Status | Note | |")
            lines.append("|---|---|---|---|")
        else:
            lines.append("| Action | Status | Note |")
            lines.append("|---|---|---|")
        for n in names:
            st, note = S.get((svc, n), ("real", ""))
            if svc == "ec2":
                lines.append(f"| `{n}` | {st} | {note} | {'M' if n in MACHINA else ''} |")
            else:
                lines.append(f"| `{n}` | {st} | {note} |")
    lines.append("")
    lines.append("### Filter names")
    lines.append("")
    lines.append("Only the `ec2` service validates filters. An `ec2` describe not listed here accepts the filters it implements and does not check names. Every listed describe also takes `tag:KEY`, `tag-key` and `tag-value`.")
    lines.append("")
    lines.append("| Describe | Filter names |")
    lines.append("|---|---|")
    for a, names in filters():
        lines.append(f"| `{a}` | {', '.join(f'`{n}`' for n in names) if names else '(none besides tag filters)'} |")
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main():
    block = render()
    doc = DOC.read_text()
    if BEGIN not in doc or END not in doc:
        sys.exit(f"{DOC} has no generated block markers")
    new = doc[:doc.index(BEGIN)] + block + doc[doc.index(END) + len(END):]
    if "--check" in sys.argv:
        if new != doc:
            print("docs/cloud-ec2-api.md action tables are out of date: run scripts/ec2/action_table.py")
            sys.exit(1)
        print("action tables are up to date")
        return
    DOC.write_text(new)
    print("rewrote the generated block:", {k: len(v) for k, v in actions().items()})


if __name__ == "__main__":
    main()
