// Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
// Proprietary software — see LICENSE in the repository root.
// https://zyvor.dev · info@zyvor.dev

//! Write a temporary mkosi project directory and run `mkosi build` via CLI (not Python internals).

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::SystemTime;

use anyhow::{anyhow, Context, Result};
use rand::Rng;

use crate::catalog::Template;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputShape {
    Qcow2,
    Raw,
}

/// Prefer install.sh / packaging symlink so minimal `PATH` still works.
fn mkosi_bin() -> PathBuf {
    for p in ["/usr/local/bin/mkosi", "/usr/bin/mkosi"] {
        let pb = Path::new(p);
        if pb.is_file() {
            return pb.to_path_buf();
        }
    }
    PathBuf::from("mkosi")
}

fn alloc_staging(vm_hint: &str) -> Result<PathBuf> {
    let safe: String = vm_hint
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .take(40)
        .collect();
    let safe = if safe.is_empty() { "rvb".into() } else { safe };
    let base = std::env::var_os("RVB_MKOSI_WORKSPACE_DIR")
        .map(PathBuf::from)
        .filter(|p| p.is_absolute())
        .unwrap_or_else(|| PathBuf::from("/var/tmp/rvb-mkosi-ws"));
    fs::create_dir_all(&base).with_context(|| format!("mkdir {}", base.display()))?;
    let id: u32 = rand::thread_rng().gen();
    let dir = base.join(format!("{safe}-{id:08x}"));
    fs::create_dir(&dir).with_context(|| format!("mkdir {}", dir.display()))?;
    Ok(dir)
}

fn write_mkosi_conf(dir: &Path, t: &Template) -> Result<()> {
    let boot = if t.bootable { "yes" } else { "no" };
    let mut pkgs = String::new();
    for p in &t.packages {
        pkgs.push_str(&format!("Packages={p}\n"));
    }
    let body = format!(
        r#"# Generated by rvb — re-run `rvb build` to regenerate.
[Distribution]
Distribution={dist}
Release={rel}

[Build]
# Alma/RHEL 9 hosts often ship systemd-repart 252; disk images need 254+. Use mkosi's default tools tree.
ToolsTree=yes

[Output]
Format={fmt}
Bootable={boot}

[Content]
{pkgs}
"#,
        dist = t.distribution,
        rel = t.release,
        fmt = t.format,
        boot = boot,
        pkgs = pkgs
    );
    let path = dir.join("mkosi.conf");
    let mut f = fs::File::create(&path).with_context(|| format!("create {}", path.display()))?;
    f.write_all(body.as_bytes())?;
    Ok(())
}

fn newest_disk_artifact(workspace: &Path) -> Result<PathBuf> {
    let mut found: Vec<(SystemTime, PathBuf)> = Vec::new();
    for sub in [
        workspace.join("build"),
        workspace.join("mkosi.build"),
        workspace.join("mkosi.output"),
        workspace.to_path_buf(),
    ] {
        collect_images(&sub, &mut found);
    }
    found.sort_by_key(|a| a.0.clone());
    found
        .into_iter()
        .next_back()
        .map(|(_, p)| p)
        .ok_or_else(|| {
            anyhow!(
                "no .raw/.qcow2 under {}/build, mkosi.build, mkosi.output, or workspace root",
                workspace.display()
            )
        })
}

fn collect_images(dir: &Path, out: &mut Vec<(SystemTime, PathBuf)>) {
    let Ok(rd) = fs::read_dir(dir) else {
        return;
    };
    for ent in rd.flatten() {
        let Ok(meta) = ent.metadata() else {
            continue;
        };
        if !meta.is_file() {
            continue;
        }
        let path = ent.path();
        let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
        if ext != "raw" && ext != "qcow2" {
            continue;
        }
        let mt = meta.modified().unwrap_or(SystemTime::UNIX_EPOCH);
        out.push((mt, path));
    }
}

/// Run `mkosi build` in `project_dir`, return path to primary disk artifact (.raw or .qcow2).
pub fn build_image(project_dir: &Path, staging_hint: &str) -> Result<PathBuf> {
    let staging = alloc_staging(staging_hint)?;
    let staging_str = staging
        .to_str()
        .ok_or_else(|| anyhow!("staging path is not UTF-8"))?;
    let dir_str = project_dir
        .to_str()
        .ok_or_else(|| anyhow!("project path is not UTF-8"))?;

    let bin = mkosi_bin();
    tracing::info!(
        bin = %bin.display(),
        "mkosi --directory {} --workspace-directory {} build",
        dir_str,
        staging_str
    );
    let st = Command::new(&bin)
        .args([
            "--directory",
            dir_str,
            "--workspace-directory",
            staging_str,
            "build",
        ])
        .status()
        .with_context(|| format!("spawn {}", bin.display()))?;

    let keep = std::env::var_os("RVB_MKOSI_KEEP_WORKSPACE").is_some();
    if !keep {
        let _ = fs::remove_dir_all(&staging);
    }

    if !st.success() {
        return Err(anyhow!("mkosi build exited with {}", st));
    }

    newest_disk_artifact(project_dir)
}

fn convert_raw_to_qcow2(src: &Path, dst: &Path) -> Result<()> {
    let st = Command::new("qemu-img")
        .args([
            "convert",
            "-O",
            "qcow2",
            src.to_str().ok_or_else(|| anyhow!("src utf-8"))?,
            dst.to_str().ok_or_else(|| anyhow!("dst utf-8"))?,
        ])
        .status()
        .context("spawn qemu-img")?;
    if !st.success() {
        return Err(anyhow!("qemu-img convert failed: {}", st));
    }
    Ok(())
}

/// Build from catalog template into `output` (parent directory must exist).
pub fn build_catalog_template(
    t: &Template,
    output: &Path,
    shape: OutputShape,
    staging_hint: &str,
) -> Result<()> {
    let tmp = tempfile::tempdir().context("tempdir for mkosi project")?;
    let dir = tmp.path();
    write_mkosi_conf(dir, t)?;
    let artifact = build_image(dir, staging_hint)?;

    match shape {
        OutputShape::Qcow2 => {
            if artifact.extension().and_then(|s| s.to_str()) == Some("qcow2") {
                fs::copy(&artifact, output)
                    .with_context(|| format!("copy to {}", output.display()))?;
            } else {
                convert_raw_to_qcow2(&artifact, output)?;
            }
        }
        OutputShape::Raw => {
            fs::copy(&artifact, output).with_context(|| format!("copy to {}", output.display()))?;
        }
    }
    Ok(())
}
