apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "machina.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "machina.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "machina.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "machina.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: machina-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.daemon.port }}
              name: https
          env:
            - name: MACHINA_JWT_SECRET
              value: {{ default .Values.auth.jwtSecret .Values.env.MACHINA_JWT_SECRET | quote }}
            - name: MACHINA_DAEMON_SKIP_AUTH
              value: {{ .Values.env.MACHINA_DAEMON_SKIP_AUTH | quote }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ default (printf "%s-config" (include "machina.fullname" .)) .Values.configMap.name }}
