[package]
license = "LicenseRef-Zyvor-Production-1.0"
name = "machina-core"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
virt = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
sha2 = "0.10"
base64 = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }
prom-remote-api = { version = "0.3", default-features = false }
prost = "0.11"
snap = { version = "1", default-features = false }
jsonwebtoken = "9.3"

[dev-dependencies]
wiremock = "0.6"
