-- DRS auto-migrate, host CPU model, fencing

ALTER TABLE clusters ADD COLUMN IF NOT EXISTS drs_auto_migrate BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS drs_cpu_threshold REAL NOT NULL DEFAULT 85.0;

ALTER TABLE hosts ADD COLUMN IF NOT EXISTS cpu_model TEXT NOT NULL DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS libvirt_version TEXT NOT NULL DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS qemu_version TEXT NOT NULL DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS fenced BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS fence_events (
    id UUID PRIMARY KEY,
    host_id UUID NOT NULL REFERENCES hosts(id),
    action TEXT NOT NULL,
    command TEXT,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
