-- Machina AI settings (BYOK, advisor mode)

ALTER TABLE clusters ADD COLUMN IF NOT EXISTS ai_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS ai_mode TEXT NOT NULL DEFAULT 'advisor';
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS ai_provider TEXT NOT NULL DEFAULT 'openai';
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS ai_model TEXT NOT NULL DEFAULT 'gpt-4o-mini';
ALTER TABLE clusters ADD COLUMN IF NOT EXISTS ai_api_key TEXT NOT NULL DEFAULT '';
