#!/usr/bin/env python3
# Copyright 2026 Zyvor AI Labs · https://zyvor.dev
# SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0
"""Stamp the Zyvor Production License v1.0 header on every tracked source file.

Idempotent: replaces the legacy "Proprietary software" header and any older SPDX
line, then writes the two-line header used across Zyvor open-source repos.

    ./scripts/add-spdx.py          # rewrite in place
    ./scripts/add-spdx.py --check  # exit 1 if any file is missing the header
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

SPDX = "LicenseRef-Zyvor-Production-1.0"
SLASH = {".rs", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".go", ".proto"}
HASH = {".py", ".sh"}
SKIP_PARTS = ("web/public/", "/vendor/", "node_modules/", "/dist/", "/target/")
SKIP_SUFFIXES = (".min.js",)

LEGACY = re.compile(
    r"^(//|#) ?("
    r"Copyright \(c\) 2026 ZyvorAI Labs Private Limited\..*"
    r"|Copyright 2026 Zyvor AI Labs.*"
    r"|Proprietary software — see LICENSE in the repository root\."
    r"|https://zyvor\.dev · info@zyvor\.dev"
    r"|SPDX-License-Identifier:.*"
    r")\s*$"
)


def header(c: str) -> list[str]:
    return [f"{c} Copyright 2026 Zyvor AI Labs · https://zyvor.dev\n", f"{c} SPDX-License-Identifier: {SPDX}\n"]


def preamble_len(lines: list[str], ext: str) -> int:
    i = 0
    if lines and lines[0].startswith("#!"):
        i = 1
    if ext == ".py" and i < len(lines) and re.match(r"^#.*coding[:=]", lines[i]):
        i += 1
    return i


def stamp(path: Path) -> bool:
    ext = path.suffix
    c = "//" if ext in SLASH else "#"
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return False
    head = text[:600].lower()
    if any(m in head for m in ("@generated", "code generated by", "do not edit")):
        return False

    lines = text.splitlines(keepends=True)
    start = preamble_len(lines, ext)
    end = start
    while end < len(lines) and end < start + 8 and LEGACY.match(lines[end]):
        end += 1
    if end > start and end < len(lines) and lines[end].strip() == "":
        end += 1

    body = lines[end:]
    sep = ["\n"] if body and body[0].strip() != "" else []
    new = "".join(lines[:start] + header(c) + sep + body)
    if new != text:
        path.write_text(new, encoding="utf-8")
        return True
    return False


def has_header(path: Path) -> bool:
    try:
        return f"SPDX-License-Identifier: {SPDX}" in path.read_text(encoding="utf-8")[:400]
    except (UnicodeDecodeError, OSError):
        return True


def tracked_sources(root: Path) -> list[Path]:
    out = subprocess.run(["git", "ls-files"], cwd=root, capture_output=True, text=True, check=True).stdout
    files = []
    for rel in out.splitlines():
        if any(p in f"/{rel}" for p in SKIP_PARTS) or rel.endswith(SKIP_SUFFIXES):
            continue
        p = root / rel
        if p.suffix in SLASH | HASH and p.is_file():
            files.append(p)
    return files


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    files = tracked_sources(root)
    if "--check" in sys.argv:
        missing = [str(f.relative_to(root)) for f in files if not has_header(f)]
        for m in missing:
            print(f"missing SPDX header: {m}")
        return 1 if missing else 0
    changed = sum(stamp(f) for f in files)
    print(f"stamped {changed} of {len(files)} source files with {SPDX}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
