// Copyright 2026 Zyvor AI Labs · https://zyvor.dev
// SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0

use serde::Serialize;
use sqlx::SqlitePool;

#[derive(Debug, Serialize)]
pub struct PolicyExport {
    pub yaml: String,
    pub rule_count: usize,
    pub quota_count: usize,
}

pub async fn export_policy_yaml(pool: &SqlitePool) -> anyhow::Result<PolicyExport> {
    let rules: Vec<(String, bool, serde_json::Value)> =
        sqlx::query_as("SELECT name, enabled, rule_json FROM policy_rules ORDER BY name")
            .fetch_all(pool)
            .await
            .unwrap_or_default();

    let quotas: Vec<(String, i32, i32, i64, i64)> = sqlx::query_as(
        "SELECT project, max_vms, max_vcpu, max_memory_mib, max_storage_gib FROM project_quotas ORDER BY project",
    )
    .fetch_all(pool)
    .await
    .unwrap_or_default();

    let mut yaml = String::from("# Machina policy export — generated by Policy Generator\napiVersion: machina.zyvor.dev/v1\nkind: ClusterPolicy\nspec:\n  rules:\n");

    for (name, enabled, rule_json) in &rules {
        yaml.push_str(&format!(
            "    - name: {}\n      enabled: {enabled}\n",
            yaml_quote_scalar(name)
        ));
        if let Ok(json_str) = serde_json::to_string(rule_json) {
            yaml.push_str(&format!("      rule: {json_str}\n"));
        }
    }

    yaml.push_str("  quotas:\n");
    for (project, max_vms, max_vcpu, max_mem, max_storage) in &quotas {
        yaml.push_str(&format!(
            "    - project: {}\n      max_vms: {max_vms}\n      max_vcpu: {max_vcpu}\n      max_memory_mib: {max_mem}\n      max_storage_gib: {max_storage}\n",
            yaml_quote_scalar(project)
        ));
    }

    let rule_count = rules.len();
    let quota_count = quotas.len();

    if let Ok(Some((req,))) = sqlx::query_as::<_, (bool,)>(
        "SELECT COALESCE(require_vm_delete_approval, false) FROM clusters ORDER BY created_at LIMIT 1",
    )
    .fetch_optional(pool)
    .await
    {
        yaml.push_str(&format!("  safeguards:\n    require_vm_delete_approval: {req}\n"));
    }

    Ok(PolicyExport {
        yaml,
        rule_count,
        quota_count,
    })
}

/// Render a string as a double-quoted YAML scalar, escaping backslashes,
/// quotes, and control characters. `policy_rules.name` / `project_quotas.project`
/// are user-controlled and were previously interpolated into this hand-built
/// YAML unescaped — a name containing `:`, `#`, a newline, or leading
/// whitespace could break the YAML structure or misrepresent the exported
/// policy. Always quoting removes the ambiguity without pulling in a full
/// YAML serializer for two scalar fields.
fn yaml_quote_scalar(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\x{:02x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
